server.port=8080

spring.datasource.url=jdbc:h2:mem:flyawaydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create

spring.jackson.serialization.write-dates-as-timestamps=false

jwt.secret=flyaway_super_secret_key_for_jwt_signing_at_least_32_bytes_long_2024
